/**
 * Export Service — Generate reports in multiple formats
 * Supports: PDF, CSV, JSON, Markdown, HTML
 */
import prisma from "@/lib/prisma";
import type { ExportOptions, HealthMetrics } from "@/types";
import { computeHealthMetrics } from "@/services/analytics";

// ─── CSV Export ───

export function generateCSV(data: Record<string, unknown>[], columns?: string[]): string {
  if (data.length === 0) return "";

  const headers = columns || Object.keys(data[0]);
  const rows = data.map((row) =>
    headers.map((h) => {
      const val = row[h];
      if (val === null || val === undefined) return "";
      const str = String(val);
      // Escape quotes and wrap in quotes if contains comma
      return str.includes(",") || str.includes('"') || str.includes("\n")
        ? `"${str.replace(/"/g, '""')}"`
        : str;
    }).join(",")
  );

  return [headers.join(","), ...rows].join("\n");
}

// ─── JSON Export ───

export function generateJSON(data: unknown, pretty: boolean = true): string {
  return JSON.stringify(data, null, pretty ? 2 : 0);
}

// ─── Markdown Export ───

export function generateMarkdownReport(
  title: string,
  sections: { heading: string; content: string; table?: { headers: string[]; rows: string[][] } }[]
): string {
  let md = `# ${title}\n\n`;
  md += `*Generated: ${new Date().toISOString()}*\n`;
  md += `*Powered by [GritGauge](https://gritgauge.dev)*\n\n---\n\n`;

  for (const section of sections) {
    md += `## ${section.heading}\n\n`;
    md += `${section.content}\n\n`;

    if (section.table) {
      md += `| ${section.table.headers.join(" | ")} |\n`;
      md += `| ${section.table.headers.map(() => "---").join(" | ")} |\n`;
      for (const row of section.table.rows) {
        md += `| ${row.join(" | ")} |\n`;
      }
      md += "\n";
    }
  }

  return md;
}

// ─── HTML Export ───

export function generateHTMLReport(
  title: string,
  sections: { heading: string; content: string; style?: string }[]
): string {
  const sectionHTML = sections
    .map(
      (s) => `
    <section style="margin-bottom: 32px; ${s.style || ""}">
      <h2 style="color: #16a34a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">${s.heading}</h2>
      <div style="color: #334155; line-height: 1.6;">${s.content}</div>
    </section>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; }
    h1 { color: #16a34a; font-size: 28px; }
    .header { text-align: center; margin-bottom: 40px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p style="color: #64748b;">Generated by GritGauge on ${new Date().toLocaleDateString()}</p>
  </div>
  ${sectionHTML}
  <div class="footer">
    <p>⚡ GritGauge — AI Co-Pilot for Open Source Maintainers</p>
  </div>
</body>
</html>`;
}

// ─── Health Report Generator ───

export async function generateHealthReport(
  repoId: string,
  repoFullName: string
): Promise<{ markdown: string; json: string; csv: string; html: string }> {
  const metrics = await computeHealthMetrics(repoId, "", "");

  const markdown = generateMarkdownReport(`Health Report: ${repoFullName}`, [
    {
      heading: "Summary",
      content: `**Health Score:** ${metrics.healthScore}/100  \n**Bus Factor:** ${metrics.busFactor}  \n**Response Time:** ${metrics.responseTimeAvg.toFixed(1)}h  \n**Stale Issue Ratio:** ${(metrics.staleIssueRatio * 100).toFixed(1)}%`,
      table: {
        headers: ["Metric", "Value"],
        rows: [
          ["Health Score", `${metrics.healthScore}/100`],
          ["Bus Factor", String(metrics.busFactor)],
          ["Response Time", `${metrics.responseTimeAvg.toFixed(1)}h`],
          ["Stale Issue Ratio", `${(metrics.staleIssueRatio * 100).toFixed(1)}%`],
          ["Contributors", String(metrics.contributorCount)],
          ["Commits/Week", String(metrics.commitFrequency)],
        ],
      },
    },
    {
      heading: "Trends",
      content: `Issues: **${metrics.trends.issuesTrend}**  \nPRs: **${metrics.trends.prsTrend}**  \nContributors: **${metrics.trends.contributorsTrend}**`,
    },
    {
      heading: "Recommendations",
      content: getRecommendations(metrics).map((r) => `- ${r}`).join("\n"),
    },
  ]);

  const json = generateJSON({ repo: repoFullName, metrics, generatedAt: new Date().toISOString() });
  const csv = generateCSV([{ ...metrics, repo: repoFullName }]);
  const html = generateHTMLReport(`Health Report: ${repoFullName}`, [
    {
      heading: "Summary",
      content: `<p><strong>Health Score:</strong> ${metrics.healthScore}/100</p><p><strong>Bus Factor:</strong> ${metrics.busFactor}</p><p><strong>Response Time:</strong> ${metrics.responseTimeAvg.toFixed(1)}h</p>`,
    },
    {
      heading: "Recommendations",
      content: `<ul>${getRecommendations(metrics).map((r) => `<li>${r}</li>`).join("")}</ul>`,
    },
  ]);

  return { markdown, json, csv, html };
}

function getRecommendations(metrics: HealthMetrics): string[] {
  const recs: string[] = [];
  if (metrics.healthScore < 40) recs.push("🔴 Critical: Health score is dangerously low. Take immediate action.");
  if (metrics.busFactor < 3) recs.push("⚠️ Bus factor is low. Onboard more core maintainers to reduce risk.");
  if (metrics.staleIssueRatio > 0.3) recs.push("⚠️ High stale issue ratio. Close inactive issues or add 'stale' labels.");
  if (metrics.responseTimeAvg > 48) recs.push("⚠️ Slow response time. Consider automated triage to speed up first responses.");
  if (metrics.contributorCount < 3) recs.push("💡 Low contributor count. Add 'good first issue' labels and promote your project.");
  if (recs.length === 0) recs.push("✅ Project looks healthy! Keep up the great work.");
  return recs;
}

// ─── Activity Report Generator ───

export async function generateActivityReport(
  repoId: string,
  repoFullName: string,
  days: number = 30
): Promise<{ markdown: string; json: string }> {
  const startDate = new Date(Date.now() - days * 86400000);

  const triageLogs = await prisma.triageLog.count({
    where: { repoId, createdAt: { gte: startDate } },
  });

  const reviewLogs = await prisma.reviewLog.count({
    where: { repoId, createdAt: { gte: startDate } },
  });

  const securityScans = await prisma.securityScan.count({
    where: { repoId, createdAt: { gte: startDate } },
  });

  const markdown = generateMarkdownReport(`Activity Report: ${repoFullName}`, [
    {
      heading: `Last ${days} Days`,
      content: `**Issues Triaged:** ${triageLogs}  \n**PRs Reviewed:** ${reviewLogs}  \n**Security Scans:** ${securityScans}`,
    },
    {
      heading: "Activity Breakdown",
      content: `Total AI-powered actions: ${triageLogs + reviewLogs + securityScans}`,
    },
  ]);

  const json = generateJSON({
    repo: repoFullName,
    period: `${days} days`,
    activity: { triageLogs, reviewLogs, securityScans },
    generatedAt: new Date().toISOString(),
  });

  return { markdown, json };
}

// ─── Export to File ───

export async function saveExportToFile(
  content: string,
  filename: string,
  format: string
): Promise<string> {
  const mimeTypes: Record<string, string> = {
    csv: "text/csv",
    json: "application/json",
    markdown: "text/markdown",
    md: "text/markdown",
    html: "text/html",
    pdf: "application/pdf",
  };

  const extension = format.startsWith(".") ? format : `.${format}`;
  const fullFilename = filename.endsWith(extension) ? filename : `${filename}${extension}`;
  const mimeType = mimeTypes[format] || "text/plain";

  // In production, save to S3/Cloud Storage
  // For now, return as data URL for download
  const base64 = Buffer.from(content, "utf-8").toString("base64");
  return `data:${mimeType};base64,${base64}`;
}
